CREATE SEQUENCE SEQ_CATEGORY;

CREATE TABLE CATEGORY (
    CATEGORY_ID BIGINT PRIMARY KEY DEFAULT nextval('SEQ_CATEGORY'),
    USER_ID BIGINT NOT NULL,
    NAME VARCHAR(15) NOT NULL,
    COLOR VARCHAR(6),
    CONSTRAINT fk_category_user FOREIGN KEY (USER_ID) REFERENCES APP_USER(USER_ID)
);

ALTER TABLE SUBSCRIPTIONS ADD CONSTRAINT fk_subscription_category
    FOREIGN KEY (CATEGORY_ID) references CATEGORY(CATEGORY_ID);

ALTER TABLE subscriptions ALTER COLUMN category_id DROP DEFAULT;
ALTER TABLE subscriptions ALTER COLUMN user_id DROP DEFAULT;

