CREATE SEQUENCE SEQ_APP_USER;

CREATE TABLE APP_USER (
    USER_ID BIGINT PRIMARY KEY DEFAULT nextval('SEQ_APP_USER'),
    EMAIL VARCHAR(255) NOT NULL UNIQUE,
    CREATION_DATE TIMESTAMP NOT NULL,
    PASSWORD_HASH VARCHAR(60) NOT NULL
);

ALTER TABLE SUBSCRIPTION ADD CONSTRAINT fk_subscription_user
    FOREIGN KEY (USER_ID) references APP_USER(USER_ID);

