CREATE SEQUENCE SEQ_SUBSCRIPTION;

CREATE TABLE SUBSCRIPTION (
    SUBSCRIPTION_ID BIGINT PRIMARY KEY DEFAULT nextval('SEQ_SUBSCRIPTION'),
    USER_ID BIGINT DEFAULT 0,
    CATEGORY_ID BIGINT DEFAULT 0,
    NAME VARCHAR(30),
    DESCRIPTION VARCHAR(50),
    AMOUNT NUMERIC(10, 2) DEFAULT 0 CHECK ( AMOUNT >= 0 ),
    CURRENCY VARCHAR(3) DEFAULT 'EUR',
    BILLING_CYCLE VARCHAR(20),
    FIRST_BILLING DATE,
    NEXT_BILLING DATE,
    IS_ACTIVE BOOLEAN,
    NOTES VARCHAR(100)

);

